swagger: "2.0"
info:
 title: Authentication API's

# tags:
#   - name: 'get users'

schemes: [http,https]
#user signUp API
paths: 
 /app/userSignUp:
  post:
    summary: Adds a new user
    produces:
      - application/json
    consumes:
      - application/json
    parameters:
      - in: body
        name: body
        schema:
          $ref: "#/components/schemas/UserSignUp"
    responses:
      '200':
        description: OK


#user login API
 /app/userSignIn:
  post:
    summary: Adds a new user
    produces:
      - application/json
    consumes:
      - application/json
    parameters:
      - in: body
        name: body
        schema:
          $ref: "#/components/schemas/userSignIn"
    responses:
      '200':
        description: OK

#Get Users List API 
 /app/users:
  get:
   summary: Returns user details
   description: users
   responses:
    200:
     description: Success
     schema:
      type: object
      properties:
       firstName:
        type: string
       lastName:
         type: string
       email:
        type: string
       password:
         type: string  
       profilePhoto:
         type: string


  # /app/userSignUp:
  #  post:
  #   summary: User sign up operations
      # produces:
      #   - application/json
      # consumes:
      #   - application/json
      # parameters:
      #   - in: body
      #     name: body
      #     schema:
      #     # $ref: "#/components/schemas/UserSignUp"
      # responses:
      #   '200':
      #     description: OK
   

components:
  schemas:
    UserSignUp:
      type: object
      required:
        - name
        - id
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        profilePhoto:
          type: string  
    userSignIn: 
      type: object
      required:
      - email
      - password
      properties:
        email:
          type: string
        password:
          type: string
         
